[2023-10-20T00:05:30.230+0000] {processor.py:153} INFO - Started process (PID=73883) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T00:05:30.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T00:05:30.231+0000] {logging_mixin.py:137} INFO - [2023-10-20T00:05:30.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T00:05:30.234+0000] {logging_mixin.py:137} INFO - [2023-10-20T00:05:30.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T00:05:30.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T00:05:30.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.019 seconds
[2023-10-20T01:31:26.247+0000] {processor.py:153} INFO - Started process (PID=73959) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T01:31:26.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T01:31:26.248+0000] {logging_mixin.py:137} INFO - [2023-10-20T01:31:26.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T01:31:26.251+0000] {logging_mixin.py:137} INFO - [2023-10-20T01:31:26.250+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T01:31:26.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T01:31:26.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.021 seconds
[2023-10-20T02:57:23.467+0000] {processor.py:153} INFO - Started process (PID=74053) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T02:57:23.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T02:57:23.469+0000] {logging_mixin.py:137} INFO - [2023-10-20T02:57:23.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T02:57:23.474+0000] {logging_mixin.py:137} INFO - [2023-10-20T02:57:23.473+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T02:57:23.477+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T02:57:23.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T04:19:26.471+0000] {processor.py:153} INFO - Started process (PID=74147) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T04:19:26.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T04:19:26.472+0000] {logging_mixin.py:137} INFO - [2023-10-20T04:19:26.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T04:19:26.475+0000] {logging_mixin.py:137} INFO - [2023-10-20T04:19:26.474+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T04:19:26.475+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T04:19:26.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.022 seconds
[2023-10-20T05:08:15.420+0000] {processor.py:153} INFO - Started process (PID=74223) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T05:08:15.421+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T05:08:15.421+0000] {logging_mixin.py:137} INFO - [2023-10-20T05:08:15.421+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T05:08:15.424+0000] {logging_mixin.py:137} INFO - [2023-10-20T05:08:15.423+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T05:08:15.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T05:08:15.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.020 seconds
[2023-10-20T06:18:01.167+0000] {processor.py:153} INFO - Started process (PID=74317) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T06:18:01.168+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T06:18:01.169+0000] {logging_mixin.py:137} INFO - [2023-10-20T06:18:01.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T06:18:01.171+0000] {logging_mixin.py:137} INFO - [2023-10-20T06:18:01.171+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T06:18:01.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T06:18:01.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.021 seconds
[2023-10-20T07:44:01.600+0000] {processor.py:153} INFO - Started process (PID=74412) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T07:44:01.601+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T07:44:01.602+0000] {logging_mixin.py:137} INFO - [2023-10-20T07:44:01.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T07:44:01.605+0000] {logging_mixin.py:137} INFO - [2023-10-20T07:44:01.605+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T07:44:01.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T07:44:01.626+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.029 seconds
[2023-10-20T09:05:40.530+0000] {processor.py:153} INFO - Started process (PID=74488) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T09:05:40.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T09:05:40.533+0000] {logging_mixin.py:137} INFO - [2023-10-20T09:05:40.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T09:05:40.537+0000] {logging_mixin.py:137} INFO - [2023-10-20T09:05:40.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T09:05:40.538+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T09:05:40.560+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.037 seconds
[2023-10-20T10:31:09.311+0000] {processor.py:153} INFO - Started process (PID=74582) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T10:31:09.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T10:31:09.312+0000] {logging_mixin.py:137} INFO - [2023-10-20T10:31:09.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T10:31:09.316+0000] {logging_mixin.py:137} INFO - [2023-10-20T10:31:09.315+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T10:31:09.316+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T10:31:09.328+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.021 seconds
[2023-10-20T11:57:00.238+0000] {processor.py:153} INFO - Started process (PID=74676) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T11:57:00.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T11:57:00.239+0000] {logging_mixin.py:137} INFO - [2023-10-20T11:57:00.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T11:57:00.242+0000] {logging_mixin.py:137} INFO - [2023-10-20T11:57:00.242+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T11:57:00.243+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T11:57:00.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.021 seconds
[2023-10-20T13:09:21.074+0000] {processor.py:153} INFO - Started process (PID=74752) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:09:21.076+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:09:21.077+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:09:21.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:09:21.082+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:09:21.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:09:21.082+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:09:21.106+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:09:51.994+0000] {processor.py:153} INFO - Started process (PID=74845) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:09:51.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:09:51.997+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:09:51.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:09:52.002+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:09:52.001+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:09:52.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:09:52.022+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:10:22.802+0000] {processor.py:153} INFO - Started process (PID=74939) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:10:22.803+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:10:22.804+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:10:22.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:10:22.808+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:10:22.807+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:10:22.809+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:10:22.825+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.028 seconds
[2023-10-20T13:10:53.543+0000] {processor.py:153} INFO - Started process (PID=75033) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:10:53.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:10:53.545+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:10:53.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:10:53.548+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:10:53.547+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:10:53.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:10:53.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-10-20T13:11:24.154+0000] {processor.py:153} INFO - Started process (PID=75109) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:11:24.156+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:11:24.157+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:11:24.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:11:24.162+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:11:24.161+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:11:24.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:11:24.183+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.035 seconds
[2023-10-20T13:11:54.824+0000] {processor.py:153} INFO - Started process (PID=75203) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:11:54.826+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:11:54.827+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:11:54.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:11:54.833+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:11:54.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:11:54.833+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:11:54.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:12:25.448+0000] {processor.py:153} INFO - Started process (PID=75297) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:12:25.450+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:12:25.451+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:12:25.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:12:25.455+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:12:25.454+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:12:25.456+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:12:25.476+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.035 seconds
[2023-10-20T13:12:56.054+0000] {processor.py:153} INFO - Started process (PID=75391) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:12:56.055+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:12:56.056+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:12:56.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:12:56.058+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:12:56.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:12:56.059+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:12:56.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-10-20T13:13:26.660+0000] {processor.py:153} INFO - Started process (PID=75467) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:13:26.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:13:26.663+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:13:26.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:13:26.668+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:13:26.667+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:13:26.669+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:13:26.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-10-20T13:13:57.300+0000] {processor.py:153} INFO - Started process (PID=75561) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:13:57.302+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:13:57.303+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:13:57.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:13:57.309+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:13:57.307+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:13:57.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:13:57.333+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-10-20T13:14:27.964+0000] {processor.py:153} INFO - Started process (PID=75655) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:14:27.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:14:27.967+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:14:27.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:14:27.971+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:14:27.970+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:14:27.971+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:14:27.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.029 seconds
[2023-10-20T13:14:58.529+0000] {processor.py:153} INFO - Started process (PID=75731) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:14:58.530+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:14:58.531+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:14:58.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:14:58.534+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:14:58.533+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:14:58.534+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:14:58.548+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-10-20T13:15:29.386+0000] {processor.py:153} INFO - Started process (PID=75825) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:15:29.388+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:15:29.389+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:15:29.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:15:29.394+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:15:29.393+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:15:29.395+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:15:29.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.037 seconds
[2023-10-20T13:15:59.998+0000] {processor.py:153} INFO - Started process (PID=75919) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:15:59.999+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:16:00.000+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:16:00.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:16:00.005+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:16:00.004+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:16:00.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:16:00.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:16:30.530+0000] {processor.py:153} INFO - Started process (PID=76013) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:16:30.530+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:16:30.531+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:16:30.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:16:30.533+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:16:30.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:16:30.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:16:30.544+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:17:01.122+0000] {processor.py:153} INFO - Started process (PID=76089) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:17:01.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:17:01.125+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:17:01.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:17:01.130+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:17:01.129+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:17:01.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:17:01.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:17:31.782+0000] {processor.py:153} INFO - Started process (PID=76183) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:17:31.784+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:17:31.785+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:17:31.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:17:31.790+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:17:31.788+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:17:31.791+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:17:31.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:18:02.452+0000] {processor.py:153} INFO - Started process (PID=76277) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:18:02.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:18:02.455+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:18:02.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:18:02.461+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:18:02.459+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:18:02.462+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:18:02.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:18:33.118+0000] {processor.py:153} INFO - Started process (PID=76371) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:18:33.119+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:18:33.120+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:18:33.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:18:33.123+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:18:33.122+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:18:33.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:18:33.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.021 seconds
[2023-10-20T13:19:03.750+0000] {processor.py:153} INFO - Started process (PID=76447) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:19:03.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:19:03.754+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:19:03.753+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:19:03.759+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:19:03.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:19:03.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:19:03.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:19:34.361+0000] {processor.py:153} INFO - Started process (PID=76541) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:19:34.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:19:34.362+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:19:34.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:19:34.364+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:19:34.364+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:19:34.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:19:34.376+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:20:04.938+0000] {processor.py:153} INFO - Started process (PID=76635) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:20:04.939+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:20:04.940+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:20:04.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:20:04.943+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:20:04.942+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:20:04.943+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:20:04.959+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.024 seconds
[2023-10-20T13:20:35.527+0000] {processor.py:153} INFO - Started process (PID=76729) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:20:35.528+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:20:35.528+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:20:35.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:20:35.531+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:20:35.531+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:20:35.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:20:35.549+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.024 seconds
[2023-10-20T13:21:06.182+0000] {processor.py:153} INFO - Started process (PID=76805) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:21:06.184+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:21:06.185+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:21:06.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:21:06.192+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:21:06.190+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:21:06.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:21:06.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.045 seconds
[2023-10-20T13:21:36.881+0000] {processor.py:153} INFO - Started process (PID=76899) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:21:36.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:21:36.883+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:21:36.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:21:36.886+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:21:36.885+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:21:36.887+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:21:36.905+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.029 seconds
[2023-10-20T13:22:07.480+0000] {processor.py:153} INFO - Started process (PID=76993) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:22:07.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:22:07.484+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:22:07.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:22:07.489+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:22:07.488+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:22:07.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:22:07.511+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.038 seconds
[2023-10-20T13:22:38.157+0000] {processor.py:153} INFO - Started process (PID=77078) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:22:38.157+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:22:38.158+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:22:38.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:22:38.160+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:22:38.159+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:22:38.160+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:22:38.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.016 seconds
[2023-10-20T13:23:08.881+0000] {processor.py:153} INFO - Started process (PID=77163) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:23:08.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:23:08.882+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:23:08.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:23:08.887+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:23:08.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:23:08.887+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:23:08.905+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-10-20T13:23:39.443+0000] {processor.py:153} INFO - Started process (PID=77257) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:23:39.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:23:39.445+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:23:39.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:23:39.451+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:23:39.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:23:39.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:23:39.474+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.038 seconds
[2023-10-20T13:24:10.059+0000] {processor.py:153} INFO - Started process (PID=77351) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:24:10.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:24:10.063+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:24:10.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:24:10.070+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:24:10.068+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:24:10.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:24:10.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-10-20T13:24:40.733+0000] {processor.py:153} INFO - Started process (PID=77427) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:24:40.734+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:24:40.735+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:24:40.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:24:40.738+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:24:40.737+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:24:40.738+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:24:40.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-10-20T13:25:11.591+0000] {processor.py:153} INFO - Started process (PID=77521) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:25:11.592+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:25:11.594+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:25:11.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:25:11.599+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:25:11.598+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:25:11.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:25:11.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:25:42.244+0000] {processor.py:153} INFO - Started process (PID=77615) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:25:42.246+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:25:42.247+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:25:42.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:25:42.250+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:25:42.250+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:25:42.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:25:42.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-10-20T13:26:12.854+0000] {processor.py:153} INFO - Started process (PID=77709) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:26:12.856+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:26:12.857+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:26:12.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:26:12.862+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:26:12.861+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:26:12.863+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:26:12.882+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.035 seconds
[2023-10-20T13:26:43.706+0000] {processor.py:153} INFO - Started process (PID=77785) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:26:43.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:26:43.707+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:26:43.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:26:43.709+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:26:43.709+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:26:43.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:26:43.721+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.018 seconds
[2023-10-20T13:27:14.479+0000] {processor.py:153} INFO - Started process (PID=77879) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:14.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:27:14.482+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:14.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:14.487+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:14.486+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:27:14.488+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:14.508+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.037 seconds
[2023-10-20T13:27:45.085+0000] {processor.py:153} INFO - Started process (PID=77973) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:45.087+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:27:45.088+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:45.088+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:45.095+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:45.093+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:27:45.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:45.121+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.045 seconds
[2023-10-20T13:27:52.457+0000] {processor.py:153} INFO - Started process (PID=78031) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:52.458+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:27:52.459+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:52.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:52.463+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:52.461+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    None
       ^
IndentationError: expected an indented block
[2023-10-20T13:27:52.463+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:52.478+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.024 seconds
[2023-10-20T13:27:56.537+0000] {processor.py:153} INFO - Started process (PID=78032) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:56.538+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:27:56.539+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:56.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:56.546+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:27:56.545+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:27:56.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:27:56.570+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.038 seconds
[2023-10-20T13:28:27.181+0000] {processor.py:153} INFO - Started process (PID=78126) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:28:27.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:28:27.183+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:28:27.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:28:27.187+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:28:27.186+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:28:27.188+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:28:27.202+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.025 seconds
[2023-10-20T13:28:58.053+0000] {processor.py:153} INFO - Started process (PID=78202) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:28:58.055+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:28:58.056+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:28:58.055+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:28:58.060+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:28:58.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:28:58.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:28:58.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-10-20T13:29:28.916+0000] {processor.py:153} INFO - Started process (PID=78295) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:29:28.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:29:28.918+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:29:28.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:29:28.921+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:29:28.920+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:29:28.921+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:29:28.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.019 seconds
[2023-10-20T13:29:59.521+0000] {processor.py:153} INFO - Started process (PID=78389) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:29:59.523+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:29:59.524+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:29:59.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:29:59.529+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:29:59.528+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:29:59.530+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:29:59.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-10-20T13:30:30.191+0000] {processor.py:153} INFO - Started process (PID=78483) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:30:30.192+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:30:30.193+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:30:30.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:30:30.198+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:30:30.197+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:30:30.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:30:30.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:31:00.823+0000] {processor.py:153} INFO - Started process (PID=78559) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:31:00.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:31:00.824+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:31:00.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:31:00.826+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:31:00.826+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:31:00.827+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:31:00.837+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.016 seconds
[2023-10-20T13:31:31.446+0000] {processor.py:153} INFO - Started process (PID=78653) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:31:31.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:31:31.448+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:31:31.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:31:31.452+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:31:31.451+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:31:31.453+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:31:31.472+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:32:02.164+0000] {processor.py:153} INFO - Started process (PID=78747) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:32:02.164+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:32:02.165+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:32:02.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:32:02.167+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:32:02.166+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:32:02.167+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:32:02.178+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:32:32.803+0000] {processor.py:153} INFO - Started process (PID=78841) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:32:32.804+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:32:32.806+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:32:32.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:32:32.813+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:32:32.811+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:32:32.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:32:32.834+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.036 seconds
[2023-10-20T13:33:03.423+0000] {processor.py:153} INFO - Started process (PID=78917) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:33:03.425+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:33:03.426+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:33:03.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:33:03.431+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:33:03.429+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:33:03.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:33:03.442+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.022 seconds
[2023-10-20T13:33:34.089+0000] {processor.py:153} INFO - Started process (PID=79011) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:33:34.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:33:34.092+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:33:34.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:33:34.096+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:33:34.095+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:33:34.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:33:34.117+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.033 seconds
[2023-10-20T13:34:04.770+0000] {processor.py:153} INFO - Started process (PID=79105) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:34:04.771+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:34:04.772+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:34:04.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:34:04.777+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:34:04.776+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:34:04.778+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:34:04.797+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.033 seconds
[2023-10-20T13:34:35.545+0000] {processor.py:153} INFO - Started process (PID=79199) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:34:35.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:34:35.546+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:34:35.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:34:35.549+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:34:35.548+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:34:35.549+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:34:35.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.015 seconds
[2023-10-20T13:35:06.390+0000] {processor.py:153} INFO - Started process (PID=79275) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:35:06.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:35:06.393+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:35:06.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:35:06.397+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:35:06.396+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:35:06.398+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:35:06.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.033 seconds
[2023-10-20T13:35:37.035+0000] {processor.py:153} INFO - Started process (PID=79368) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:35:37.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:35:37.037+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:35:37.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:35:37.042+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:35:37.040+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:35:37.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:35:37.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:36:07.641+0000] {processor.py:153} INFO - Started process (PID=79462) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:36:07.642+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:36:07.643+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:36:07.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:36:07.648+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:36:07.647+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:36:07.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:36:07.664+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.028 seconds
[2023-10-20T13:36:38.287+0000] {processor.py:153} INFO - Started process (PID=79556) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:36:38.288+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:36:38.290+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:36:38.289+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:36:38.295+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:36:38.293+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:36:38.295+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:36:38.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:37:09.037+0000] {processor.py:153} INFO - Started process (PID=79632) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:37:09.038+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:37:09.039+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:37:09.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:37:09.044+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:37:09.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:37:09.044+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:37:09.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-10-20T13:37:39.788+0000] {processor.py:153} INFO - Started process (PID=79726) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:37:39.789+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:37:39.790+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:37:39.790+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:37:39.795+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:37:39.794+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:37:39.796+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:37:39.817+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.035 seconds
[2023-10-20T13:38:10.425+0000] {processor.py:153} INFO - Started process (PID=79820) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:38:10.426+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:38:10.426+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:38:10.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:38:10.429+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:38:10.428+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:38:10.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:38:10.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:38:41.083+0000] {processor.py:153} INFO - Started process (PID=79914) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:38:41.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:38:41.084+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:38:41.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:38:41.087+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:38:41.086+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:38:41.087+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:38:41.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.018 seconds
[2023-10-20T13:39:11.756+0000] {processor.py:153} INFO - Started process (PID=79990) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:39:11.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:39:11.757+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:39:11.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:39:11.760+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:39:11.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:39:11.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:39:11.773+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.020 seconds
[2023-10-20T13:39:42.606+0000] {processor.py:153} INFO - Started process (PID=80084) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:39:42.607+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:39:42.608+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:39:42.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:39:42.613+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:39:42.611+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:39:42.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:39:42.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:40:13.260+0000] {processor.py:153} INFO - Started process (PID=80178) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:40:13.261+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:40:13.262+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:40:13.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:40:13.267+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:40:13.266+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:40:13.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:40:13.287+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:40:43.864+0000] {processor.py:153} INFO - Started process (PID=80272) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:40:43.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:40:43.867+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:40:43.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:40:43.874+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:40:43.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:40:43.875+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:40:43.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-10-20T13:41:14.576+0000] {processor.py:153} INFO - Started process (PID=80348) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:41:14.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:41:14.579+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:41:14.578+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:41:14.584+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:41:14.583+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:41:14.585+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:41:14.604+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:41:45.311+0000] {processor.py:153} INFO - Started process (PID=80442) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:41:45.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:41:45.338+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:41:45.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:41:45.345+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:41:45.342+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:41:45.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:41:45.386+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-10-20T13:42:15.894+0000] {processor.py:153} INFO - Started process (PID=80536) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:42:15.895+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:42:15.895+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:42:15.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:42:15.900+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:42:15.898+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:42:15.900+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:42:15.914+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-10-20T13:42:46.539+0000] {processor.py:153} INFO - Started process (PID=80630) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:42:46.539+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:42:46.540+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:42:46.540+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:42:46.542+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:42:46.542+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:42:46.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:42:46.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:43:17.212+0000] {processor.py:153} INFO - Started process (PID=80706) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:43:17.214+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:43:17.214+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:43:17.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:43:17.219+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:43:17.218+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:43:17.220+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:43:17.239+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:43:47.838+0000] {processor.py:153} INFO - Started process (PID=80800) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:43:47.840+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:43:47.841+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:43:47.841+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:43:47.847+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:43:47.845+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:43:47.847+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:43:47.866+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:44:18.542+0000] {processor.py:153} INFO - Started process (PID=80894) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:44:18.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:44:18.545+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:44:18.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:44:18.549+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:44:18.548+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:44:18.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:44:18.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:44:49.447+0000] {processor.py:153} INFO - Started process (PID=80988) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:44:49.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:44:49.448+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:44:49.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:44:49.451+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:44:49.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:44:49.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:44:49.462+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:45:20.305+0000] {processor.py:153} INFO - Started process (PID=81064) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:45:20.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:45:20.307+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:45:20.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:45:20.312+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:45:20.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:45:20.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:45:20.332+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-10-20T13:45:50.872+0000] {processor.py:153} INFO - Started process (PID=81157) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:45:50.874+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:45:50.875+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:45:50.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:45:50.880+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:45:50.879+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:45:50.881+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:45:50.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:46:21.466+0000] {processor.py:153} INFO - Started process (PID=81251) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:46:21.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:46:21.469+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:46:21.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:46:21.474+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:46:21.473+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:46:21.475+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:46:21.494+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.033 seconds
[2023-10-20T13:46:52.137+0000] {processor.py:153} INFO - Started process (PID=81346) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:46:52.137+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:46:52.138+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:46:52.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:46:52.140+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:46:52.139+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:46:52.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:46:52.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.016 seconds
[2023-10-20T13:47:22.808+0000] {processor.py:153} INFO - Started process (PID=81422) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:47:22.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:47:22.811+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:47:22.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:47:22.817+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:47:22.815+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:47:22.818+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:47:22.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.038 seconds
[2023-10-20T13:47:53.481+0000] {processor.py:153} INFO - Started process (PID=81517) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:47:53.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:47:53.484+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:47:53.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:47:53.490+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:47:53.488+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:47:53.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:47:53.510+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:48:24.101+0000] {processor.py:153} INFO - Started process (PID=81611) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:48:24.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:48:24.104+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:48:24.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:48:24.109+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:48:24.108+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:48:24.110+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:48:24.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:48:55.028+0000] {processor.py:153} INFO - Started process (PID=81687) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:48:55.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:48:55.029+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:48:55.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:48:55.032+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:48:55.031+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:48:55.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:48:55.043+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.017 seconds
[2023-10-20T13:49:25.836+0000] {processor.py:153} INFO - Started process (PID=81781) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:49:25.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:49:25.838+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:49:25.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:49:25.843+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:49:25.842+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:49:25.844+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:49:25.864+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:49:56.482+0000] {processor.py:153} INFO - Started process (PID=81875) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:49:56.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:49:56.485+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:49:56.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:49:56.490+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:49:56.488+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:49:56.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:49:56.511+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.034 seconds
[2023-10-20T13:50:27.144+0000] {processor.py:153} INFO - Started process (PID=81969) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:50:27.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:50:27.146+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:50:27.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:50:27.152+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:50:27.150+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:50:27.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:50:27.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-10-20T13:50:57.842+0000] {processor.py:153} INFO - Started process (PID=82045) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:50:57.843+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:50:57.844+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:50:57.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:50:57.850+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:50:57.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:50:57.851+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:50:57.872+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.035 seconds
[2023-10-20T13:51:28.483+0000] {processor.py:153} INFO - Started process (PID=82139) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:51:28.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:51:28.484+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:51:28.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:51:28.486+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:51:28.485+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:51:28.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:51:28.497+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.016 seconds
[2023-10-20T13:51:51.046+0000] {processor.py:153} INFO - Started process (PID=82215) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:51:51.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:51:51.047+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:51:51.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:51:51.085+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:51:51.084+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:51:51.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:51:51.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.052 seconds
[2023-10-20T13:52:21.767+0000] {processor.py:153} INFO - Started process (PID=82309) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:52:21.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:52:21.769+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:52:21.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:52:21.795+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:52:21.794+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:52:21.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:52:21.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-10-20T13:52:52.320+0000] {processor.py:153} INFO - Started process (PID=82403) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:52:52.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:52:52.321+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:52:52.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:52:52.341+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:52:52.340+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:52:52.341+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:52:52.356+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-10-20T13:53:22.968+0000] {processor.py:153} INFO - Started process (PID=82479) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:53:22.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:53:22.970+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:53:22.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:53:22.992+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:53:22.991+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:53:22.992+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:53:23.003+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.039 seconds
[2023-10-20T13:53:53.634+0000] {processor.py:153} INFO - Started process (PID=82573) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:53:53.636+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:53:53.637+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:53:53.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:53:53.663+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:53:53.662+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:53:53.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:53:53.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2023-10-20T13:54:24.295+0000] {processor.py:153} INFO - Started process (PID=82667) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:54:24.296+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:54:24.297+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:54:24.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:54:24.325+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:54:24.323+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:54:24.325+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:54:24.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2023-10-20T13:54:54.968+0000] {processor.py:153} INFO - Started process (PID=82761) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:54:54.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:54:54.970+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:54:54.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:54:54.991+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:54:54.990+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:54:54.991+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:54:55.004+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.039 seconds
[2023-10-20T13:55:25.642+0000] {processor.py:153} INFO - Started process (PID=82837) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:55:25.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:55:25.645+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:55:25.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:55:25.669+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:55:25.668+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:55:25.670+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:55:25.685+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2023-10-20T13:55:56.314+0000] {processor.py:153} INFO - Started process (PID=82931) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:55:56.315+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:55:56.316+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:55:56.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:55:56.342+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:55:56.341+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:55:56.342+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:55:56.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2023-10-20T13:56:27.035+0000] {processor.py:153} INFO - Started process (PID=83025) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:56:27.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:56:27.038+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:27.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:56:27.062+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:27.062+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    with DAG('user_processing', start_date=datetime('2023, 01, 01'),
TypeError: an integer is required (got type str)
[2023-10-20T13:56:27.063+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:56:27.077+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2023-10-20T13:56:37.221+0000] {processor.py:153} INFO - Started process (PID=83044) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:56:37.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:56:37.223+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:56:37.251+0000] {processor.py:753} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:56:37.318+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.318+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:user_processing
[2023-10-20T13:56:37.322+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.321+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:user_processing
[2023-10-20T13:56:37.324+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.324+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:user_processing
[2023-10-20T13:56:37.324+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.324+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-10-20T13:56:37.330+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.330+0000] {dag.py:2711} INFO - Creating ORM DAG for user_processing
[2023-10-20T13:56:37.335+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:56:37.335+0000] {dag.py:3441} INFO - Setting next_dagrun for user_processing to 2023-10-19T00:00:00+00:00, run_after=2023-10-20T00:00:00+00:00
[2023-10-20T13:56:37.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.124 seconds
[2023-10-20T13:57:07.729+0000] {processor.py:153} INFO - Started process (PID=83129) to work on /opt/airflow/dags/user_processing.py
[2023-10-20T13:57:07.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-10-20T13:57:07.730+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:57:07.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-10-20T13:57:07.755+0000] {processor.py:753} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-10-20T13:57:07.770+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:57:07.770+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-10-20T13:57:07.784+0000] {logging_mixin.py:137} INFO - [2023-10-20T13:57:07.784+0000] {dag.py:3441} INFO - Setting next_dagrun for user_processing to 2023-10-19T00:00:00+00:00, run_after=2023-10-20T00:00:00+00:00
[2023-10-20T13:57:07.795+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/user_processing.py took 0.068 seconds
